# Generated by Django 5.0.7 on 2024-07-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_bookappointment_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paybill', models.CharField(max_length=255)),
                ('acc_number', models.CharField(max_length=255)),
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.bookappointment')),
            ],
        ),
    ]
