# Generated by Django 5.0.7 on 2024-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='acc_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='paybill',
            field=models.CharField(max_length=20),
        ),
    ]
