# Generated by Django 5.0.7 on 2024-07-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billinginformation_acc_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginformation',
            old_name='appointment',
            new_name='services',
        ),
    ]
