# Generated by Django 5.0.7 on 2024-07-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_bookappointment_age_and_more'),
        ('billing', '0004_remove_billinginformation_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.bookappointment'),
        ),
    ]
