# Generated by Django 5.0.7 on 2024-07-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_for', models.CharField(choices=[('MYSELF', 'Myself'), ('OTHER', 'Other')], max_length=6)),
                ('id_number', models.PositiveIntegerField()),
                ('service', models.CharField(choices=[('GENERAL CONSULTATION', 'General consultation'), ('MODERN LAB', 'Modern lab'), ('PHARMACY', 'Pharmacy'), ('SPECIALIST', 'Specialist services')], max_length=30)),
                ('appointment_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual')], max_length=8)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('area_of_residence', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('NOT APPROVED', 'Not approved')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paybill', models.CharField(max_length=255)),
                ('acc_number', models.CharField(max_length=255)),
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.bookappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('NOT APPROVED', 'Not approved')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.bookappointment')),
            ],
        ),
    ]
