# Generated by Django 5.0.7 on 2024-07-29 23:11

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginformation',
            name='appointment',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='age',
            field=models.BigIntegerField(validators=[appointments.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='id_number',
            field=models.BigIntegerField(validators=[appointments.models.validate_id_number]),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='BillingInformation',
        ),
    ]
