# Generated by Django 5.0.7 on 2024-07-29 23:17

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_bookappointment_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='age',
            field=models.PositiveIntegerField(validators=[appointments.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='id_number',
            field=models.PositiveIntegerField(validators=[appointments.models.validate_id_number]),
        ),
    ]
